name: $(date:yyyy.M.d)-$(Build.SourceBranchName)-$(date:HHmm)

trigger:
  batch: true
  paths:
    include:
      - '*'
  branches:
    include:
      - feature/*
      - hotfix/*
      - main
      
stages:
  - template: /pipelines/stages/build.yaml
    parameters:
      sourceFolder: /solutions/landingZone

  # - template: stages/deploy.yaml
  #   parameters:
  #     env: dev

  # - template: stages/deploy.yaml
  #   parameters:
  #     env: prd